development:
  port: 8081
  user: tenbew
  pass: tenbew678
  ip: 41.156.64.242
  url: http://41.156.64.242:8081/WaspInterface
  callback_url: https://asgard-mocha.net/cellc_cb1
  endpoint: http://41.156.64.242:8081/WaspInterface
  wsdl: http://41.156.64.242:8081/WaspInterface?wsdl
  namespace: http://wasp.doi.soap.protocol.cellc.co.za
  local_ssh_enabled: true
  charge_code: DOI005

test:
  port: 8081
  user: tenbew
  pass: tenbew678
  ip: 10.228.76.132
  charge_code: DOI005
  url: http://41.156.64.242:8081/WaspInterface
  callback_url: https://asgard-mocha.net/cellc_cb1
  endpoint: http://10.228.76.132:8081/WaspInterface
  wsdl: http://10.228.76.132:8081/WaspInterface?wsdl
  namespace: http://doi.net.truteq.com/
  local_ssh_enabled: false

production:
  port: 443
  user: tenbew
  pass: tenbew678
  ip: 41.156.64.242
  ip_2: 41.156.64.246
  charge_code: TENB00500
  url: https://41.156.64.242:443/WaspInterface
  url_2: https://41.156.64.246:443/WaspInterface
  callback_url: https://asgard-mocha.net/cellc_cb1
  endpoint: https://41.156.64.242:443/WaspInterface
  wsdl: https://41.156.64.242:443/WaspInterface?wsdl
  namespace: http://wasp.doi.soap.protocol.cellc.co.za
