development:
  port: 22
  ip: 156.38.208.218
  waspTID: QQChina
  serviceID: '00'
  MN: CellC_ZA
  charge_code: DOI005
  charge_value: R5

test:
  port: 22
  ip: 156.38.208.218
  waspTID: QQChina
  serviceID: 00
  MN: CellC_ZA
  charge_code: DOI005
  charge_value: R5
  
production:
  port: 22
  ip: 156.38.208.218
  waspTID: QQChina
  serviceID: 00
  MN: CellC_ZA
  charge_code: DOI005
  charge_value: R5
